apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporter
  template:
    metadata:
      labels:
        app: reporter
    spec:
      containers:
        - name: reporter
          image: testframeworkacr66b5d.azurecr.io/testframework/reporter:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "chown grafana /var/lib/grafana; chgrp grafana /var/lib/grafana;service grafana-server start;while true; do sleep 30; done;" ]
          resources:
            limits:
              cpu: "4"
              memory: 2G
          volumeMounts:
            - name: grafana-volume
              mountPath: /var/lib/grafana
          ports:
            - containerPort: 3000
            - containerPort: 8086
              name: api
      volumes:
      - name: grafana-volume
        persistentVolumeClaim:
          claimName: azure-grafana-disk
      tolerations:
        - key: "sku"
          operator: "Equal"
          value: "reporter"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: reporter
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: reporter